apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: v1beta3-demo-template
  title: New Resource Group
  description: scaffolder v1beta3 template to create resource group
  tags:
    - azure
    - infrastructure
    - cet
    - resource-group
    - recommended
spec:
  owner: backstage/techdocs-core
  type: service
  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Fill Resource Group Information
      required:
        - name
        - location
        - environment
      properties:
        name:
          title: Name
          type: string
          description: Resource Group Name
          pattern: '^([a-zA-Z][a-zA-Z0-9]*)(-[a-zA-Z0-9]+)*$'
          ui:autofocus: true
          ui:options:
            rows: 5
          ui:errorMessages:
            pattern: "First letter must be a letter, and only letters and numbers are allowed delimited by hyphens"
        location:
          title: Location
          type: string
          description: Resource Group Location
          default: westeurope
          enum:
            - westeurope
            - northeurope
            - swedencentral
          enumNames:
            - West Europe
            - North Europe
            - Sweden Central
        subscription:
          title: SubscriptionId
          type: string
          description: Enter Subscription ID
          ui:autofocus: true
          ui:widget: text
        environment:
          title: Environment
          type: string
          description: Resource Group Environment
          default: dev
          enum:
            - dev
            - test
            - prod
            - poc
          enumNames:
            - Development
            - Testing
            - Production
            - POC
      errorMessage:
        properties:
          name: 'First letter must be a letter, and only letters and numbers are allowed delimited by hyphens'
    - title: Fill solution information
      required:
        - solutionID
        - owner
      properties:
        solutionID:
          title: Solution ID
          type: string
          description: Solution ID or RFD number
          ui:autofocus: true
          ui:options:
            rows: 5
        owner:
          title: Owner
          type: string
          description: Solution owner
          ui:autofocus: true
          ui:widget: text
          ui:help: 'Enter multiple owners separated by comma'
          ui:options:
            rows: 10
        businesContext:
          title: Business Context
          type: string
          description: Business Context
          ui:autofocus: true
          ui:widget: textarea
          ui:options:
            rows: 4
          ui:help: 'Enter business context'

  # here's the steps that are executed in series in the scaffolder backend
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          name: ${{ parameters.name }}

    - id: fetch-docs
      name: Fetch Docs
      action: fetch:plain
      input:
        targetPath: ./community
        url: https://github.com/backstage/community/tree/main/backstage-community-sessions

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'